sudo: required
language: c
install:
    - sudo apt-get update cmake
    - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
    - tar xvf cmocka-1.0.1.tar.xz
    - cd cmocka-1.0.1
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DWITH_STATIC_LIB=1 ..
    - sudo make install
    - cd ../..
    - rm -rf cmocka-1.0.1
script:
    - cd test
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./bin/run_tests
